name: PR checks
on: pull_request

jobs:
  run-image:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Build image
        run: DOCKER_BUILDKIT=1 docker build --tag canonical.design .

      - name: Run image
        run: |
          docker run --detach --network host canonical.design
          sleep 1
          curl --head --fail --retry-delay 1 --retry 30 --retry-connrefused http://localhost

