name: PR checks
on: [push, pull_request]s

jobs:
  run-image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build image
        run: DOCKER_BUILDKIT=1 docker build --tag canonical.design .

      - name: Run image
        run: |
          docker run --detach --network host canonical.design
          sleep 1
          curl --head --fail --retry-delay 1 --retry 30 --retry-connrefused http://localhost
          
    run-dotrun:
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v4

        - name: Install dotrun
          run: sudo pip3 install dotrun requests==2.31.0

        - name: Install dependencies
          run: |
            sudo chmod -R 777 .
            dotrun install

        - name: Build assets
          run: dotrun build

        - name: Run dotrun
          run: |
            dotrun &
            curl --head --fail --retry-delay 1 --retry 30 --retry-connrefused http://localhost:8052

lint-scss:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: yarn install --immutable

      - name: Lint scss
        run: yarn lint-scss

  lint-js:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: yarn install --immutable

      - name: Lint JS
        run: |
          yarn lint-js

  lint-python:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dotrun
        run: sudo pip3 install dotrun

      - name: Install dependencies
        run: |
          sudo chmod -R 777 .
          dotrun install

      - name: Build assets
        run: dotrun build

      - name: Lint python
        run: dotrun lint-python

  lint-jinja:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Install node dependencies
        run: yarn install --immutable

      - name: Install python dependencies
        run: |
          python3 -m pip install --upgrade pip
          sudo pip3 install djlint

      - name: Get changed HTML files in the templates folder
        id: changed-files
        uses: tj-actions/changed-files@v43
        with:
          files: templates/**/*.html

      - name: Lint jinja
        if: steps.changed-files.outputs.any_changed == 'true'
        env:
          CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          echo "The following files have changed: $CHANGED_FILES"
          djlint $CHANGED_FILES --lint --profile="jinja"

  inclusive-naming-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: woke
        uses: canonical-web-and-design/inclusive-naming@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-check
          fail-on-error: false